In [37]:
import numpy as np
import ast as ast

#--declaring list of years
List_Year = list(range(2000,2010))

print("List_Year --> " + str(List_Year))
print(" ")

print("Type of List_Year --> " + str(type(List_Year)))
print(" ")

List_Year_Len = len(List_Year)
print("Length of List_Year --> " + str(List_Year_Len))
print(" ")

dict_content = "{"

for i in range(0,List_Year_Len):
    if (i == List_Year_Len - 1):
        dict_content = dict_content + "'" + str(List_Year[i]) + "'" + ":" + str(i) + "}"
    else:
        dict_content = dict_content + "'" + str(List_Year[i]) + "'" + ":" + str(i) + ","

print("dict_content --> " + str(dict_content))
print(" ")
        
#--declaring dictionary of years
Dict_Year_Col = ast.literal_eval(dict_content) 

print("Dict_Year_Col --> " + str(Dict_Year_Col))
print(" ")

print("Type of Dict_Year_Col --> " + str(type(Dict_Year_Col)))
print(" ")

print("Dict_Year_Col['2000'] --> " + str(Dict_Year_Col['2000']))
print(" ")

List_Year --> [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]

Type of List_Year --> <class 'list'>

Length of List_Year --> 10

dict_content --> {'2000':0,'2001':1,'2002':2,'2003':3,'2004':4,'2005':5,'2006':6,'2007':7,'2008':8,'2009':9}

Dict_Year_Col --> {'2000': 0, '2001': 1, '2002': 2, '2003': 3, '2004': 4, '2005': 5, '2006': 6, '2007': 7, '2008': 8, '2009': 9}

Type of Dict_Year_Col --> <class 'dict'>

Dict_Year_Col['2000'] --> 0

In [38]:
#--declaring list of names
List_Name = ['Arun','Barun','Kiran','Mala']

print("List_Name --> " + str(List_Name))
print(" ")

print("Type of List_Name --> " + str(type(List_Name)))
print(" ")

List_Name_Len = len(List_Name)
print("Length of List_Name --> " + str(List_Name_Len))
print(" ")

#--declaring variable
dict_content_1 = "{"

for i in range(0,List_Name_Len):
    if (i == List_Name_Len - 1):
        dict_content_1 = dict_content_1 + "'" + str(List_Name[i]) + "'" + ":" + str(i) + "}"
    else:
        dict_content_1 = dict_content_1 + "'" + str(List_Name[i]) + "'" + ":" + str(i) + ","

#--declaring row dictionary variable        
Dict_Name_Row = ast.literal_eval(dict_content_1)

print("Dict_Name_row --> " + str(Dict_Name_row))
print(" ")

print("Type of Dict_Name_row --> " + str(type(Dict_Name_Row)))
print(" ")

print("Dict_Name_Row['Arun'] --> " + str(Dict_Name_Row['Arun']))
print(" ")

List_Name --> ['Arun', 'Barun', 'Kiran', 'Mala']

Type of List_Name --> <class 'list'>

Length of List_Name --> 4

Dict_Name_row --> {'Arun': 0, 'Barun': 1, 'Kiran': 2, 'Mala': 3}

Type of Dict_Name_row --> <class 'dict'>

Dict_Name_Row['Arun'] --> 0

In [44]:
#--creating lists with salaries of 'Arun', 'Barun', 'Kiran', 'Mala' for the time period (2000 - 2009)
Arun_salary = [45000,56000,60750,65430,70500,78000,84500,89000,91000,95780]
Barun_salary = [42350,53800,66300,65480,75500,78900,84560,89700,91100,95680]
Kiran_salary = [44350,53890,67300,65570,75680,78780,84570,89680,91250,97180]
Mala_salary = [42750,56990,67890,65564,75780,78810,84520,89710,91390,97600]

print("Salary of Arun between (2000 - 2009) : Arun_salary --> " + str(Arun_salary))
print(" ")

print("Salary of Barun between (2000 - 2009) : Arun_salary --> " + str(Barun_salary))
print(" ")

print("Salary of Kiran between (2000 - 2009) : Arun_salary --> " + str(Kiran_salary))
print(" ")

print("Salary of Mala between (2000 - 2009) : Arun_salary --> " + str(Mala_salary))
print(" ")

Salary_matrix = np.array([Arun_salary,Barun_salary,Kiran_salary,Mala_salary])

print("All salaies : Salary_Matrix --> ")
print(" ")

print(str(Salary_matrix))
print(" ")

Salary of Arun between (2000 - 2009) : Arun_salary --> [45000, 56000, 60750, 65430, 70500, 78000, 84500, 89000, 91000, 95780]

Salary of Barun between (2000 - 2009) : Arun_salary --> [42350, 53800, 66300, 65480, 75500, 78900, 84560, 89700, 91100, 95680]

Salary of Kiran between (2000 - 2009) : Arun_salary --> [44350, 53890, 67300, 65570, 75680, 78780, 84570, 89680, 91250, 97180]

Salary of Mala between (2000 - 2009) : Arun_salary --> [42750, 56990, 67890, 65564, 75780, 78810, 84520, 89710, 91390, 97600]

All salaies : Salary_Matrix -->

[[45000 56000 60750 65430 70500 78000 84500 89000 91000 95780]
 [42350 53800 66300 65480 75500 78900 84560 89700 91100 95680]
 [44350 53890 67300 65570 75680 78780 84570 89680 91250 97180]
 [42750 56990 67890 65564 75780 78810 84520 89710 91390 97600]]

In [79]:
print("The salary of Arun in the year 2000 --> " + str(Salary_matrix[Dict_Name_Row['Arun'],Dict_Year_Col['2000']]))
print(" ")

print("The salary of Arun in the year 2009 --> " + str(Salary_matrix[Dict_Name_Row['Arun'],Dict_Year_Col['2009']]))
print(" ")

print("The max salary of Arun --> " + str(Salary_matrix[Dict_Name_Row['Arun'],:].max()))
print(" ")

print("The min salary of Arun --> " + str(Salary_matrix[Dict_Name_Row['Arun'],:].min()))
print(" ")

print("The mean salary of Arun --> " + str(Salary_matrix[Dict_Name_Row['Arun'],:].mean()))
print(" ")

x, y = np.where(Salary_matrix == Salary_matrix[Dict_Name_Row['Arun'],:].max())
print("The year when Arun received the max salary --> " + list(Dict_Year_Col.keys())[list(Dict_Year_Col.values()).index(y)])
print(" ")

Kiran_max_sal = Salary_matrix[Dict_Name_row['Kiran'],:].max()
x, y = np.where(Salary_matrix == Kiran_max_sal)
Kiran_max_sal_year = list(Dict_Year_Col.keys())[list(Dict_Year_Col.values()).index(y)]
print("Kiran got her max salary on --> " + str(Kiran_max_sal_year))
print(" ")

Max_sal_on_2005 = Salary_matrix[:,Dict_Year_Col['2005']].max()
print("Max salary on 2005 --> " + str(Max_sal_on_2005))
print(" ")

Min_sal_on_2009 = Salary_matrix[:,Dict_Year_Col['2009']].min()
print("Min salary on 2009 --> " + str(Min_sal_on_2009))
print(" ")

The salary of Arun in the year 2000 --> 45000

The salary of Arun in the year 2009 --> 95780

The max salary of Arun --> 95780

The min salary of Arun --> 45000

The mean salary of Arun --> 73596.0

The year when Arun received the max salary --> 2009

Kiran got her max salary on --> 2009

Max salary on 2005 --> 78900

Min salary on 2009 --> 95680